// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_layout.tsx";
import * as $3 from "./routes/api/reset.ts";
import * as $4 from "./routes/championship.tsx";
import * as $5 from "./routes/greet/[name].tsx";
import * as $6 from "./routes/history.tsx";
import * as $7 from "./routes/index.tsx";
import * as $8 from "./routes/result.tsx";
import * as $9 from "./routes/update/[name].tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_layout.tsx": $2,
    "./routes/api/reset.ts": $3,
    "./routes/championship.tsx": $4,
    "./routes/greet/[name].tsx": $5,
    "./routes/history.tsx": $6,
    "./routes/index.tsx": $7,
    "./routes/result.tsx": $8,
    "./routes/update/[name].tsx": $9,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
